### ISSUE TITLE
Info from ePubs

### ISSUE THREAD

**Issue by dainiusjocas** [dainiusjocas/evilreader#5]
How to get this info from ePub file:
1. Author
2. Title
3. Year
4. Cover image

**Comment by V-GG** [comment]
If you use the class Book from the epublib-core-latest.jar you can get that infromation with simply calling a couple of funcitons like Book.getCoverImage() or for the rest there is Book.getMetadata() where you can get the rest of the information you need. To instance a Book class you need to write new EpubReader()).readEpub(inputStream) where inputStream is the file form the memory.

**Comment by dainiusjocas** [comment]
Perfect I'll try to implement it. Thanks

**Comment by dainiusjocas** [comment]
EvilBook aEvilBook = new EvilBook(pEvilPath);
authors = aEvilBook.getAuthors().trim();
title = aEvilBook.getTitle();
year = aEvilBook.getYear();

and cover image is left for future
